### ISSUE TITLE
WebExtension Migration

### ISSUE THREAD

**Issue by Jacosci** [0xffffabcd/steamrep-checker-firefox#5]
As we already know, Firefox 57.0 will only suppoort WebExtensions addons.
Is there any plan to port this addon to WebExtensions?

**Comment by 0xffffabcd** [comment]
Yes, there are plans to update this extension to work with Firefox 57+

**Comment by 0xffffabcd** [comment]
@Jacosci The new version that is compatible with Firefox 57.0 is [here](https://github.com/0xffffabcd/steamrep-checker)
